---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    # Has docker compose preinstalled
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        # Refer to existing action
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        # Checks our code out in side our GitHub actions job
        uses: actions/checkout@v2
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"